### PR TITLE
Start SML language track, add accumulate problem

### PR DESCRIPTION
**Pull request by mcmillhj**
There is now an example program *accumulate.sml* and test program *test_accumulate.sml* for the exercism accumulate problem. Since this is the first SML problem I also added some configuration:
   1. I updated .travis.yml to have sml instead of bash for the language
   2. I updated README.md to outline how testing for SML works, at least for the first problem.  A better solution is probably warranted, there are a few SML unit testing frameworks, but I was hesitant to add another dependency; Also, I don't know if that is possible with exercism (or how to do it).

I wasn't really sure how to start off a new language track, I hope this was the proper approach.

### CODE REVIEW

**Comment by mcmillhj** [comment]
The Travis build failed, so I apparently configured something incorrectly :|

**Comment by kytrinyx** [comment]
Thanks for contributing!

If you go grab the [configlet](https://github.com/exercism/configlet/releases) binary, it will help point you to common configuration issues.

In this case you need to name `accumulate.sml` to `example.sml`.

Here's the relevant section of the contributing doc: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md#submitting-new-problems

**Comment by mcmillhj** [comment]
This should be ok to merge now right?

**Comment by kytrinyx** [comment]
Yeah, sorry--I don't get notifications when something has been rebased :/

Thanks for this!

**Comment by mcmillhj** [comment]
No worries. Thanks for merging. I will try to keep the changes all in one commit from now on.

**Pull request merged**
