### PR TITLE
implementation of anagram problem for SML track

### PR DESCRIPTION
**Pull request by mcmillhj**
Two new files have been added: test_anagram.sml that will test a correct implemention of the anagram problem, and example.sml a sample solution.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Would you mind rebasing this onto master? The config got a conflict.

**Comment by mcmillhj** [comment]
Just to clarify, that would be me rebasing my xsml/anagram branch on my fork? Would I need another step after that to affect this PR?

**Comment by kytrinyx** [comment]
Oh, yeah, no worries.

So on your fork, you would `git fetch upstream` (or whatever you call this repository as opposed to your own). Then you would say:

```
git rebase upstream/master
```

This takes all the new commits from master, and puts them below your commits in this branch, and then re-applies each commit.

When it hits a snag it stops and waits for you to fix the conflict.

If you get stuck let me know, I can either walk you through the details or do it myself locally.

**Comment by mcmillhj** [comment]
Awesome! Thanks for the pointers. Since I work on one problem at a time in it's own branch, and update the config for each problem won't this always conflict on the second branch merged? Or did I make some mistake in this branch specifically that caused this?

**Comment by kytrinyx** [comment]
No, it will almost always conflict, unless you don't add the new one as the last exercise.

**Comment by mcmillhj** [comment]
I see, well I will just work on a single problem at a time to avoid this. Question, I followed your instructions listed above, fixed the merge conflict, then executed `git rebase --continue`, it looks like the rebase succeeded without error but I don't see any changes I need to push when I say `git status`. Is there a final step that I am missing?

**Comment by kytrinyx** [comment]
Ah, yeah, my bad: `git push -f origin yourbranchname`

**Comment by mcmillhj** [comment]
No worries, thanks!

**Pull request merged**
