### PR TITLE
Added an about.md

### PR DESCRIPTION
**Pull request by remcopeereboom**

### CODE REVIEW

**Comment by remcopeereboom** [comment]
Accidentally also added a LEARNING.md to the master. Let me know if you want me to separate the two.

**Comment by kytrinyx** [comment]
I think it's fine. For clarity, would you mind rebasing onto the most recent master to get rid of the merge commit, and change the title of the PR to be "Add user-facing documentation" (or something to that effect)?

**Comment by remcopeereboom** [comment]
Will resubmit as asked.

**Comment by kytrinyx** [comment]
@remcopeereboom You do not need to resubmit—you can force push to the same branch, which updates the pull request.

**Comment by remcopeereboom** [comment]
@kytrinyx I always mess that up.

**Pull request closed without merging**
